export const products = [
  {
    productImage: "/img/product/product1/1.jpg",
    rating: 5,
    reviews: 200,
    price: 660,
    title: "Woven Throw Pillow",
    isFavorite: true,
    productLink: "/",
    badgeText: "NEW",
    badgeClass: "bg-success",
    // colors: [
    //   { image: "/img/product/1.png", color: "#184A48" },
    //   { image: "/img/product/1.png", color: "#DB4444" },
    // ],
  },
  {
    productImage: "/img/product/product2/1.jpg",
    rating: 4,
    reviews: 70,
    price: 350,
    title: "Copley Dining Chair",
    isFavorite: true,
    productLink: "/",
    badgeText: "SOLD",
    badgeClass: "bg-secondary",
  },
  {
    productImage: "/img/product/product3/1.jpg",
    rating: 4.5,
    reviews: 70,
    price: 700,
    title: "Women's Flexible Bottom Shoes",
    isFavorite: true,
    productLink: "/",
    badgeText: "NEW",
    badgeClass: "bg-success",
  },
  {
    productImage: "/img/product/product4/1.jpg",
    rating: 5,
    reviews: 200,
    price: 500,
    title: "Women's Strap Sandal",
    isFavorite: true,
    productLink: "/",
    badgeText: "NEW",
    badgeClass: "bg-success",
  },
  {
    productImage: "/img/product/product5/1.jpg",
    rating: 5,
    reviews: 200,
    price: 500,
    title: "Cat Eye Reading Glasses",
    isFavorite: true,
    productLink: "/",
    badgeClass: "bg-success",
    badgeText: "NEW",
  },
  {
    productImage: "/img/product/product6/1.jpg",
    rating: 5,
    reviews: 200,
    price: 1160,
    title: "Girls' Monster Wallet",
    isFavorite: true,
    productLink: "/",
    badgeText: "NEW",
    badgeClass: "bg-success",
  },
  {
    productImage: "/img/product/product7/1.jpg",
    rating: 5,
    reviews: 200,
    price: 660,

    title: "Room Stick Lamp",
    isFavorite: true,
    productLink: "/",
    badgeText: "NEW",
    badgeClass: "bg-success",
  },
  {
    productImage: "/img/product/product8/1.jpg",
    rating: 5,
    reviews: 200,
    price: 660,
    title: "Army Baseball Cap",
    isFavorite: true,
    productLink: "/",
    badgeClass: "bg-success",
  },
];
