export const products = [
    {
      productImage: "/img/single/1.jpeg",
      rating: 5,
      reviews: 200,
      price: 660,
      title: "Woven Throw Pillow",
      isFavorite: true,
      productLink: "/",
      badgeText: "NEW",
      badgeClass: "bg-success",
    },
    {
      productImage: "/img/single/2.jpeg",
      rating: 4,
      reviews: 70,
      price: 350,
      title: "Copley Dining Chair",
      isFavorite: true,
      productLink: "/",
      badgeText: "SOLD",
      badgeClass: "bg-secondary",
    },
    {
      productImage: "/img/single/3.jpeg",
      rating: 4.5,
      reviews: 70,
      price: 700,
      title: "Women's Flexible Bottom Shoes",
      isFavorite: true,
      productLink: "/",
      badgeText: "NEW",
      badgeClass: "bg-success",
    },
    {
      productImage: "/img/single/4.jpeg",
      rating: 5,
      reviews: 200,
      price: 500,
      title: "Women's Strap Sandal",
      isFavorite: true,
      productLink: "/",
      badgeText: "NEW",
      badgeClass: "bg-success",
    },
  ];
  